### ISSUE TITLE
Error on importing gmusicapi

### ISSUE THREAD

**Issue by mrhmouse** [malcolmstill/thunner#10]
Original error message:

```
$ thunner  
Traceback (most recent call last):
  File "/usr/local/bin/thunner", line 39, in <module>
    from gmusicapi.api import Api
ImportError: No module named api
```

I fixed this by changing `gmusicapi.api` to `gmusicapi`.

**Comment by mrhmouse** [comment]
Actually, scratch that. Apparently `gmusicapi.Api` is deprecated now. I may submit a pull request sometime in the near future migrating to the new system.

```
$ thunner
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/thunner", line 446, in <module>
    main()
  File "/usr/local/bin/thunner", line 290, in main
    api = apiinit(config['email'],config['pass'])
  File "/usr/local/bin/thunner", line 108, in apiinit
    api = Api()
  File "/usr/lib/python2.7/site-packages/gmusicapi/__init__.py", line 21, in __init__
    raise ImportError('gmusicapi.Api is deprecated; use gmusicapi.Webclient'
ImportError: gmusicapi.Api is deprecated; use gmusicapi.Webclient or gmusicapi.Musicmanager instead.
For help rewriting your code, see https://unofficial-google-music-api.readthedocs.org/en/latest/usage.html#quickstart.
For an explanation of why the change was made, see https://github.com/simon-weber/Unofficial-Google-Music-API/issues/112.
```

**Comment by malcolmstill** [comment]
Fixed now. Apologies for the delay @mrhmouse.
