### ISSUE TITLE
Crash while building trees 

### ISSUE THREAD

**Issue by HalfAdd3r** [malcolmstill/thunner#11]
Software crashes while building trees due to key error.  Trace below

Traceback (most recent call last):
  File "/home/pi/git/thunner/thunner", line 442, in <module>
    main()
  File "/home/pi/git/thunner/thunner", line 293, in main
    artists, albums = gen_trees(library)
  File "/home/pi/git/thunner/thunner", line 233, in gen_trees
    "subtree":sorted(tracks,key=itemgetter('track')),
KeyError: 'track'

**Comment by simon-weber** [comment]
Ah, `track` isn't guaranteed as a key in the song dictionaries. Here's the relevant docs: [gmusicapi metadata fields](https://unofficial-google-music-api.readthedocs.org/en/develop/reference/metadata.html#gmusicapi.protocol.metadata.KnownMetadataFields).

Unfortunately, [there's no way to provide a default value to itemgetter](http://bugs.python.org/issue14384), so you'll have to figure out another way to sort the tracks.

**Comment by akelling** [comment]
Also seeing this error on first run.... :/

**Comment by malcolmstill** [comment]
Any idea how I can recreate the error?

**Comment by HalfAdd3r** [comment]
I've manually uploaded some songs to my collection.  I think as long as a song doesn't have a track listing in it's metadata it will trigger the problem.

**Comment by malcolmstill** [comment]
Can you try the issue11 branch (with version 2.0.0 of gmusicapi)? I'm struggling to recreate the crash; I've tried stripping the tags from a couple of songs and uploading them but they seem to be given a track number of 0 as default.

**Comment by HalfAdd3r** [comment]
Sorry to say this has the same result.  

Traceback (most recent call last):
  File "/home/pi/git/thunner/thunner11", line 442, in <module>
    main()
  File "/home/pi/git/thunner/thunner11", line 293, in main
    artists, albums = gen_trees(library)
  File "/home/pi/git/thunner/thunner11", line 233, in gen_trees
    "subtree":sorted(tracks,key=itemgetter('track')),
KeyError: 'track'

I've been able to get it to work by changing ln 233 from "track" to "title"
